### ISSUE TITLE
Getting public full-stack CI going

### ISSUE THREAD

**Issue by wfarr** [boxen/our-boxen#364]
Need to chat with @scottjg about setting up a Mac Mini with ESX somewhere so our-boxen will automatically be able to do some integration CI for all branches.

**Comment by radeksimko** [comment]
FYI, you may find this useful: https://github.com/radeksimko/vagrant-osx

**Comment by petems** [comment]
@radeksimko I've been using @AndrewDryga's Vagrant boxes in his tests so far :+1: ( https://github.com/boxen/our-boxen/issues/713)

**Comment by petems** [comment]
@radeksimko Oh awesome, sorry I just looked at your repo, I think that is the missing part to get boxen working with Beaker! :+1:

**Comment by radeksimko** [comment]
I didn't notice the @AndrewDryga's repo before. It looks nice, although I had always more luck making it work under VMWare, the license in this case **was seriously worth the money** (for both VMWare Fusion + Vagrant plugin). Trying to make OSX VM work under Virtualbox was just always too painful.

I don't think Apple would be happy to see licensed SW (although available for free for all Mac users) freely available in form of Virtualbox baseboxes. I think it's good to keep the whole process up to user due to transparency and licensing.

I don't think you actually want to bother with [setting up XCode each time](https://github.com/AndrewDryga/vagrant-box-osx#how-to-accept-the-xcode-license-from-the-cli) you run tests, it should probably [be part of the basebox as XCode CLI Tools](https://github.com/timsutton/osx-vm-templates/blob/master/scripts/xcode-cli-tools.sh).

It's pointing out one important bit though, that's a support for older OSX versions which I'm dealing with at the moment. I do have `10.9` box built and waiting for response from Apple support as they seems they locked me away from downloading `10.8` even though I paid for the license in the past.

Generally don't get me wrong, I appreciate the work you've done, @AndrewDryga, I'm just trying to explain why I took the approach I took. ;-)

If you think there's something missing/wrong there, feel free to send a PR and/or fork it, it's OSS at the end.

**Comment by AndrewDryga** [comment]
@radeksimko I'm feeling lucky because it's always works for me :). Setup takes time, but VM works as expected. Also, XCode is part of my box, and It's license is already accepted in Yosemite (v0.2.0).

Actually it would be right to crosslink our repos, so people can choose between VMWare and VirtualBox. But my repo is far away from yours, because you have scripts to build this boxes and I just host 9GB box file.

About licensing: you have right to have up to two VM's of Mac OS on your Apple hardware. Everything else in uncertain.

P.S.: Added link to you'r repo in my Readme.md.

**Comment by radeksimko** [comment]
> Also, XCode is part of my box, and It's license is already accepted in Yosemite (v0.2.0).

Nice, but it doesn't help transparency too much. User imo want/should be able to build it locally if necessary (updates, some custom enhancements... etc), that's why I rather link to the `timsutton/osx-vm-templates` repo to let people do it. Have a look there, AFAIK there's even a Virtualbox builder in the packer template so you might be able to leverage that as well.

> About licensing: you have right to run up to two VM's of Mac OS on your Apple hardware. Everything else in uncertain.

Agreed, but I'm not sure it means you can distribute such VM to people that eventually may not have agreed with the license (who effectively may not have bought Mac). Generally I'm not really much into legal stuff, so I don't personally really care, but I just wanted to point it out as a potential issue/threat for the repo and your account.

Github was lately taking down whole accounts due licensing issues. See https://help.github.com/articles/dmca-takedown-policy/

> Actually it would be right to crosslink our repos, so people can choose between VMWare and VirtualBox. But my repo is far away from yours, because you have scripts to build this boxes and I just host 9GB box file that was made manually.

Generally speaking I'm ok with making it my current repo more generic to support virtualbox too as long as I'm able to spin up a box that actually works or at least come up with a consistent set of commands that will make it work on a fresh latest OS X installation & latest Virtualbox & latest Vagrant.

I will have a look at your setup and also links at the end of your Readme.

**Comment by petems** [comment]
@radeksimko @AndrewDryga Do you have any ideas about getting to the keychain to work?

```
osx-1010-x64 20:07:55$ cd /opt/boxen/repo && YOLO=true ./script/boxen --no-fde --debug --token=TOKEN
--> Preparing to auto-update...
--> Skipping auto-update, since this isn't a git checkout yet


serverspec at /opt/boxen/repo/.bundle/ruby/2.0.0/bundler/gems/serverspec-b1f10d640f48 did not have a valid gemspec.
This prevents bundler from installing bins or native extensions, but that may not affect its functionality.
The validation message from Rubygems was:
  ["wercker.yml"] are not files
--> You have an existing Homebrew install in /usr/local
    The Boxen provides its own Homebrew, so consider deleting yours.
    Keeping both will confuse many projects.

Boxen Keychain Helper: Encountered error code: -25308
Error: User interaction is not allowed.
/opt/boxen/repo/.bundle/ruby/2.0.0/gems/boxen-2.7.0/lib/boxen/keychain.rb:48:in `set': Can't save GitHub API Token in the keychain. (Boxen::Error)
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/boxen-2.7.0/lib/boxen/keychain.rb:30:in `token='
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/boxen-2.7.0/lib/boxen/config.rb:73:in `save'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/boxen-2.7.0/lib/boxen/cli.rb:48:in `run'
	from ./script/boxen:165:in `<main>'
```

**Comment by AndrewDryga** [comment]
@petems did you unlock keychain before this script? What keychain do you use? (Login, System or your own?)

**Comment by petems** [comment]
@AndrewDryga I've figured something out, I'm changing the test to use the vagrant user rather than root :+1:

**Comment by radeksimko** [comment]
@petems https://github.com/radeksimko/vagrant-osx/blob/master/provision/setup-keychain.sh

**Comment by petems** [comment]
@radeksimko Yep, I just had to make sure I was running as vagrant, it didn't work for root.

Acceptance tests with Beaker and Vagrant now working, branch here: https://github.com/petems/our-boxen/tree/add_beaker_tests

Going to clean up and open a PR soon :+1:

**Comment by AndrewDryga** [comment]
Hey, @petems. I've noticed that you are puppet guru, and I may have few questions about it. So it looks like eventually It's me who will own you a beer :). Is there any way to contact you?

**Comment by petems** [comment]
@AndrewDryga Sure, tweet me and I'll DM my email https://twitter.com/petersouter :+1:

**Comment by petems** [comment]
https://github.com/boxen/our-boxen/pull/720 PR now :+1:

**Comment by seanknox** [comment]
#720 is where this work is now happening.
