### ISSUE TITLE
script/boxen exits with 2 even on success 

### ISSUE THREAD

**Issue by petems** [boxen/our-boxen#722]
This makes writing tests a little tricky:

```ruby
1) boxen sanity check runs with no errors
     Failure/Error: shell("cd /opt/boxen/repo && BOXEN_NO_PULL=true ./script/boxen --no-fde --debug --token=#{ENV['GITHUB_API_TOKEN']}", :acceptable_exit_codes => [0])
     Beaker::Host::CommandFailure:
       Host 'osx-1010-x64' exited with 2 running:
        cd /opt/boxen/repo && BOXEN_NO_PULL=true ./script/boxen --no-fde --debug --token=5f7887922aa6da5927dfdfb8dd78dc8b688854c9
       Last 10 lines of output were:
       	Debug: Class[Main]: The container Stage[main] will propagate my refresh event
       	Debug: Finishing transaction 70258635014900
       	Debug: Storing state
       	Info: Creating state file /tmp/boxen/puppet/var/state/state.yaml
       	Debug: Stored state in 0.06 seconds
       	--> You haven't loaded Boxen's environment yet!
       	    To permanently fix this, source /opt/boxen/env.sh at the end
       	    of your shell's startup file.

       	--> Run source /opt/boxen/env.sh or restart your shell for new stuff!
```

**Comment by seanknox** [comment]
This one has always driven me a bit nuts. Thinking about digging into it—any idea from where that exit code is generated?

**Comment by seanknox** [comment]
puppet returns an error every time:

`Boxen::Util.sudo`:
```ruby
def self.sudo *args
   system "sudo", "-p", "Password for sudo: ", *args
end
```

Which runs puppet with the follow commands:

`/opt/boxen/repo/bin/puppet apply --group admin --confdir /tmp/boxen/puppet/conf --vardir /tmp/boxen/puppet/var --libdir /opt/boxen/repo/lib --libdir /opt/boxen/repo/.bundle/ruby/2.0.0/gems/boxen-2.7.1/lib --modulepath /opt/boxen/repo/modules:/opt/boxen/repo/shared --hiera_config /opt/boxen/repo/config/hiera.yaml --logdest /opt/boxen/repo/log/boxen.log --logdest console --no-report --detailed-exitcodes --show_diff /opt/boxen/repo/manifests`

**Comment by seanknox** [comment]
Aha! It's a puppet thing.

```
puppet-apply(8) -- Apply Puppet manifests locally
========
--detailed-exitcodes:
  Provide transaction information via exit codes. If this is enabled, an exit
  code of '2' means there were changes, an exit code of '4' means there were
  failures during the transaction, and an exit code of '6' means there were both
  changes and failures.
```

Make sure you accept exit codes `0` and `2`, e.g. `:acceptable_exit_codes => [0,2]`.

```ruby
module Boxen
  class Puppeteer
    class Status < Struct.new(:code)
      # Puppet's detailed exit codes reserves 2 for a successful run with changes
      def success?
        [0,2].include?(code)
      end
    end
 end
end
```

**Comment by seanknox** [comment]
There are a lot of entangled code to fix this, perhaps @rafaelfranca or @dgoodlad knows the proper fix.

**Comment by rafaelfranca** [comment]
Could you explain why we need to return 0? I believe we should keep playing nice with puppet exit codes.

**Comment by seanknox** [comment]
Agree we should play nice with Puppet (and think we can) but it's indeed odd that Puppet breaks UNIX convention that a successful run returns a non-zero exit code. Boxen itself ultimately returns Puppet's exit code when it finishes, so to an user—or a test—it appears to be in error.

At the end of `Boxen::CLI`:

```ruby
      if flags.run?
        # Run the postflight checks.
        Boxen::Postflight.run config if status.success?
      end

      # Return Puppet's exit status.
      return status.code
    end
```

We know whether puppet ran successfully or not during the postflight checks—`Puppeteer::Status.success?` returns true if puppet returns 0—ran successfully and no system changes—or 2—ran successfully with system changes. The returning of `status.code` is redundant and problematic. While in puppetland an exit code of 2 is a fine thing, for every other UNIX utility, it's a means failure. Boxen should catch puppet's exit code and do the right thing, and Boxen's exit should then follow UNIX convention: 0 for success and 1 on error.

There's a lot of confusion going on in `Boxen::Runner`, too. I see a lot of opportunity for refactoring: long methods into smaller ones, naming, better use of composition, replacing type code with state/strategy, etc. Hoping I can help tackle that eventually.

@petems in the meantime, you may want to adjust your tests so that 0 or 2 is a successful run. Short term hack but will at least allow for integration testing (which I'm VERY much looking forward to using).

**Comment by rafaelfranca** [comment]
:+1:

**Comment by jacebrowning** [comment]
> in the meantime, you may want to adjust your tests so that 0 or 2 is a successful run

This seems to work for me:

`$ boxen; test $? -le 2`

**Comment by petems** [comment]
Yeah, this is a Puppet exit with detailed exit codes thing, so working as intended 👍
