### ISSUE TITLE
Install after a boxen nuke not working

### ISSUE THREAD

**Issue by elsom25** [boxen/our-boxen#783]
Performed a nuke, which led to a few issues (#782). Resolved those, but now:

```bash
cd /opt/boxen/repo/
./script/boxen
--> Preparing to auto-update...
--> Complete! Nothing new from upstream.
script/bootstrap: line 93: bundle: command not found
find: bin: No such file or directory
Could not find rake-10.3.2 in any of the sources
Run `bundle install` to install missing gems.
```

To note, this was all post updating to Osx `10.11`.

**Comment by elsom25** [comment]
And weird solution part 2, in case anyone else stumbles on this particular weirdness.

I had to add `/Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/bin` to my path in order for my console to find `bundle`, which was sufficient to let me run `./script/boxen`

**Comment by richardtoner** [comment]
There was me beginning to think that an OS X upgrade was completely trouble free for the first time! I had to go and ruin that warm fuzzy feeling by attempting to install a few new apps with my broken Boxen :disappointed: 

I decided to nuke it and start again. I then ran into the same issue as @elsom25 when attempting to run the Boxen script.

It seems the addition of `/Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/bin` to my PATH fixed the issue, so thanks to @elsom25 for sharing that! However, I would not class that as a perfect solution as it requires an additional undocumented step aside from the README.

I would think it is worth reopening this issue so that a more elegant solution can be sought out.

**Comment by seanknox** [comment]
Upgraded to Xcode 7 on 10.10 Yosemite and encountered the same issue; path fix mentioned by @elsom25 did the trick. 

cc @tarebyte @mikemcquaid

**Comment by mikemcquaid** [comment]
@seanknox FYI I'm not longer actively maintaining Boxen any more. The solution here is probably to extend https://github.com/boxen/our-boxen/pull/759 somehow

**Comment by jacobbednarz** [comment]
@seanknox can you see if #804 will solve this for you?

**Comment by seanknox** [comment]
@jacobbednarz I'm no longer using Boxen as well. Thanks for checking in!

**Comment by jacobbednarz** [comment]
Thanks, closing.
