### ISSUE TITLE
boxen module exists twice in module paths

### ISSUE THREAD

**Issue by jarrettone** [boxen/our-boxen#789]
It appears the boxen module appears twice in the module search path. The below output shows that the custom facter facts are being picked up twice, resulting in an error about a constant and the facts.d dir being parsed twice.

    $ boxen
    --> Preparing to auto-update...
    --> Complete! Nothing new from upstream.
    Fact file /opt/boxen/repo/facts.d/example.yaml was parsed but returned an empty data set
    /opt/boxen/repo/shared/boxen/lib/facter/boxen_facts_d.rb:11: warning: already initialized constant BoxenFactsDirectoryLoader::EXTERNAL_FACT_WEIGHT
    /opt/boxen/repo/modules/boxen/lib/facter/boxen_facts_d.rb:11: warning: previous definition of EXTERNAL_FACT_WEIGHT was here
    Fact file /opt/boxen/repo/facts.d/example.yaml was parsed but returned an empty data set
    Notice: Compiled catalog for [REDACTED] in environment production in 1.98 seconds

Is this intentional?

**Comment by eugeneius** [comment]
`/opt/boxen/repo/modules/boxen/` shouldn't exist; it certainly doesn't in this repo: https://github.com/boxen/our-boxen/tree/master/modules

You can safely remove that directory, which will fix the warning.

**Comment by jarrettone** [comment]
I think it got pulled in in one of the librarian-puppet runs. I'll rebuild from scratch and verify.

**Comment by jarrettone** [comment]
@eugeneius looks like it gets pulled in as part of the librarian-puppet run when trying to update to current our-boxen per the FAQ*. This seems like either the Puppetfile should not include boxen and the module should just be part of shared or it shouldn't be in shared.

* https://github.com/boxen/our-boxen/blob/master/docs/faq.md#q-how-do-you-upgrade-your-boxen-from-the-public-our-boxen

**Comment by eugeneius** [comment]
It looks like that FAQ entry is wrong.

When you run the `boxen` command, it tells `librarian-puppet` to install modules into the `shared/` directory:
https://github.com/boxen/boxen/blob/2.8.0/lib/boxen/puppeteer.rb#L105

The FAQ entry is telling you to run `librarian-puppet` without passing the `--path` option, which means it will use the default path for modules - which is `modules/`:
https://github.com/rodjek/librarian-puppet/blob/v1.0.9/lib/librarian/puppet/environment.rb#L20

I've never run into this problem because I always run `boxen`, whether I'm integrating upstream changes or making them myself.

Do you want to submit a pull request adding that flag to the command in the FAQ?

**Comment by jacobbednarz** [comment]
@eugeneius That would be great if you could! :tada:

**Comment by eugeneius** [comment]
I was suggesting that @jarrettone could do it... but okay :grin: https://github.com/boxen/our-boxen/pull/811

**Comment by jacobbednarz** [comment]
ah, my apologies! thanks.

**Comment by jarrettone** [comment]
Apologies gents, been away for a while. Toddlers are time thieves.

I was about to say that I'll gladly update the faq, but @eugeneius beat me to it. @jacobbednarz any chance on getting that merged in the not-too-distant? Is there more that needs to be done here to get it merged?

**Comment by jacobbednarz** [comment]
Consider it done. Thanks! :)
