### ISSUE TITLE
Remove Puppetfile.lock from repository

### ISSUE THREAD

**Issue by sambauers** [boxen/our-boxen#799]
There is no need for this file in the repository as all the version numbers are locked in `Puppetfile` itself.

In our setup, where we have copied our-boxen into a non-forked private repository, merging the Puppetfile.lock is a real pain, and ultimately useless as we just regenerate it with a `librarian-puppet install` run anyway.

**Comment by jacobbednarz** [comment]
Thanks for the feedback @sambauers. I'm not really comfortable removing the `Puppetfile.lock` from the repository since it is good for the majority of people who are just forking the vanilla `our-boxen` setup and possibly not running `librarian-puppet` locally. 

If you are having issues maintaining a forked version, I'd recommend checking out the [FAQ article](https://github.com/boxen/our-boxen/blob/master/docs/faq.md#q-how-do-you-upgrade-your-boxen-from-the-public-our-boxen) on upgrading as it gives quite a good approach on handling the situation you've described.

I'm going to close this one off but I'm happy to answer any questions you may have.
